### ISSUE TITLE
gold train: [story:AB001] Atomic Bomb - intro

### ISSUE THREAD

**Issue by lhaze** [lhaze/challenge-games#13]
*If* the Reich was to build an atomic bomb, it might not have a chance to use it. Let's suppose there are some facts to discover  and some artifacts left by the project to gain. High rate of improbability.

**Comment by lhaze** [comment]
Intro card

```yaml
title: "*Uranverein*"
type: "historical > project"
discovery gain:
  - 1 influence
  - 1 improbability
keywords:
  - scientific
conditions:
  - scientist ally or scientist char
flavor: >
  Foo bar
sources:
  - https://en.wikipedia.org/wiki/German_nuclear_weapons_program
```
